name: mimicdev
dependencies:
    - python=2.7.12
    - nose
    - sqlalchemy
    - pandas
    - sympy
    - mako
    - scikit-learn
    - matplotlib
    - toolz
    - decorator
    - pip:
        - autopep8
        - git+https://github.com/scikit-learn-contrib/py-earth.git
        - git+https://github.com/jcrudy/clinvoc.git
        - git+https://github.com/mattlewissf/ccs.git
        - git+https://github.com/jcrudy/sklearntools.git
